require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - lib/process_balancer/private/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 145
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 4
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Metrics:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Max: 2
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  EnforcedStyle: to_not
RSpec/StubbedMock:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: true
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/SlicingWithRange:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
